### ISSUE TITLE
"Skip this version" does nothing on Linux/Windows

### ISSUE THREAD

**Issue by jcaw** [talonvoice/talon#183]
Not sure if it applies to other platforms

**Comment by jeheydorn** [comment]
It's not working on Windows either. The update pop-up reappears every time I start up Talon. I'm on version 0.1.3.

I would just take the update every time, but doing so requires working with my company's security team to approve every version of each DLL and executable run by the talon update. Gotta love antiviruses...

By the way, they say that they can't create a rule in the antivirus software to always allow Talon upgrades because the DLLs and executables are not digitally signed. I'm not sure if that's something you can address or if it even make sense to do so, but it would be nice if it could be done.

**Comment by lunixbochs** [comment]
Can you point at specific DLLs and executables that aren't signed that they care about? I'm signing the main stuff right now on windows. macOS signs everything already. I'm happy to look into signing everything on windows. That's worth filing a separate issue with some info, and I'll try get it sorted by next release (0.1.5)

It would help to either have a list of all of the things they had to make exceptions for, or at least a list of the file extensions they care about.

**Comment by jeheydorn** [comment]
Sorry for the delay. Here's the list:

talon.exe
talon_console.exe
libtalon.dll
extract.exe
libdraconity.dll

**Comment by lunixbochs** [comment]
@jeheydorn can you have them check out the just-released beta? version `107-0.1.4-41-gf9c6`, pinned in the #beta channel.

Should have signatures for everything, even the stuff you didn't list, all using the Talon EV certificate.
