### ISSUE TITLE
Provide line numbers for talon file deprecation warnings

### ISSUE THREAD

**Issue by fidgetingbits** [talonvoice/talon#313]
Sometimes it's possible to see warnings like this in talon files if characters are not escaped properly:

```
2021-05-19 12:33:27 DEBUG [~] /home/aa/.talon/user/fidget/text/symbols.talon
2021-05-19 12:33:27 WARNING <unknown>:1: DeprecationWarning: invalid escape sequence \(
```

You noted that this may be a python deprecation warning rather than coming from talon itself, but since it's coming from a talon file it would be nice if it was possible to somehow get the exact line number in the talon file that it is coming from.

**Comment by lunixbochs** [comment]
Fixed in next beta. This one was kind of annoying, because it's buried in a parser and Python's ast module prints this warning before we get any visibility over the output.

Note it also has a second line number of `1`, the only way to fix that would be to pad every string with the appropriate number of newlines at the start.
```
2021-05-23 11:30:48 WARNING user/error.talon:6:1: DeprecationWarning: invalid escape sequence \(
```
