### ISSUE TITLE
Can't have more than one arithmetic symbol (+-*) on a Talonscript line

### ISSUE THREAD

**Issue by splondike** [talonvoice/talon#325]
Consider the following two examples of .talon files:
```
test:
  a = 1 + 2
  a = a + 3
```
```
test:
  a = 1 + 2 + 3
```
The former works, but the latter is a syntax error. This is a bit unexpected. My actual use case was concatenating strings (which I now know we have "{a} {b} {c}" syntax for).

**Comment by lunixbochs** [comment]
This is intentional. TalonScript is designed for very simple use only - the expressiveness is limited to keep the language easily machine transformable and guide you toward using Python for anything complicated.

Multiple operators within an expression opens up a lot of complexity in the language, like order of operations, parentheses, deeply nested syntax. A similar example is you can't nest action calls, you can only call an action as part of a statement (with optional assignment).
