### ISSUE TITLE
Mac: Talon triggers switch to discrete GPU

### ISSUE THREAD

**Issue by nriley** [talonvoice/talon#363]
When I try to [draw on the screen with Talon](https://github.com/nriley/knausj_talon/blob/nriley/modes/modes.py#L103) it triggers a switch to the discrete GPU on my MacBook Pro 16ʺ.  This takes enough time (a second or two) that it delays the drawing and confuses me.

Can Talon set [NSSupportsAutomaticGraphicsSwitching](https://developer.apple.com/library/archive/qa/qa1734/_index.html) to prevent switching?  I tried changing it myself but Talon refuses to launch when it's modified.

Thanks!

**Comment by lunixbochs** [comment]
Just adding the flag won't be enough, I'll need to actually support automatic graphics switching

**Comment by nriley** [comment]
Gotcha… that'd be useful then.

**Comment by lunixbochs** [comment]
I confirmed that adding NSSupportsAutomaticGraphicsSwitching did not help. I'm using `MTLCreateSystemDefaultDevice()`, which gives me a dgpu by default.

I need to:
1. Use MTLCopyAllDevicesWithObserver.
2. If the computer is on battery (not plugged in), I should always prefer an iGPU (device.isLowPower).
3. Otherwise, detect if the dGPU is active, and use that if so. If no dGPU is active, use the first iGPU.
4. If the dGPU becomes active in the future, and we are not on battery, switch to it.
5. If we are using the dGPU, and the device switches from power to battery, switch to the iGPU.
6. If the device switches from battery back to power, switch back to the dGPU if it's still active.
7. If/when we are the last program using the dGPU (if it's possible to detect this), possibly switch to the iGPU. Possibly only do this if the device is on battery power.

**Comment by lunixbochs** [comment]
After reading https://developer.apple.com/documentation/metal/gpu_selection_in_macos/selecting_device_objects_for_graphics_rendering

I think Talon should prefer whichever GPU is driving a given display, and register for NSApplicationDidChangeScreenParametersNotification to see if that changes

(I think we may need to also reinit the canvas if it is moved onto a new monitor)

**Comment by lunixbochs** [comment]
I think this will solve itself with apple silicon
