### ISSUE TITLE
Talon on Windows prefers default communications device over default device

### ISSUE THREAD

**Issue by timo95** [talonvoice/talon#419]
The `microphone->system default` setting does not use the default device, but the default communications device. This can be reproduced by setting some non default audio device as default communications device in the old audio settings menu. The default communications device is for calls while the default device is for everything else.

Windows 10
Talon 0.2.0-150

**Comment by lunixbochs** [comment]
Microsoft says the default communications device is for general voice use, not just calls. I'm not sure this manifests as a substantially different issue than someone who has their overall default mic set to something unexpected. I'm not sure I see this as a bug.

Keep in mind Talon's own microphone menu selections persist across Talon restarts and remember your preferences across multiple microphones - so that's the preferred way of selecting a microphone these days.

**Comment by timo95** [comment]
Microsoft's distinction between default device and default communications device is IMHO pretty useless for input devices. Especially since the modern settings menu does not allow you to set the default communications device at all. Instead they included the option to set the input device for each app separately which should remove the need for a default communications device.

**Comment by timo95** [comment]
But you are apparently correct that it is for general voice use.

**Comment by lunixbochs** [comment]
I've attempted to change this in the next beta anyway. Will see if anyone complains about having it the other way.
