### ISSUE TITLE
Calling ctrl.cursor_visible(True) when cursor is already visible throws error in log

### ISSUE THREAD

**Issue by fidgetingbits** [talonvoice/talon#427]
Arch linux
Version: 0.2.0-161-gc4ed, Branch: pro, OS: Linux-5.14.16-arch1-1-x86_64-with-glibc2.33

This is minor and it doesn't impact functionality at all afaict, but with dual monitors if I don't see the cursor I will occasionally think it is invisible and say `cursor show`, and if it's not actually hidden I get the following error in the talon log:

```
2021-11-16 17:07:07 ERROR x11 event error
    8:                     lib/python3.9/threading.py:930|
    7:                     lib/python3.9/threading.py:973|
    6:                     lib/python3.9/threading.py:910|
    5:                         talon/linux/xclient.py:429| # [stack splice]
    4: lib/python3.9/site-packages/xcffib/__init__.py:571|
    3: lib/python3.9/site-packages/xcffib/__init__.py:605|
    2: lib/python3.9/site-packages/xcffib/__init__.py:686|
    1: lib/python3.9/site-packages/xcffib/__init__.py:649|
xcffib.xproto.MatchError
```

It doesn't seem like there's something exposed in `ctrl` that we can query from python to tell if it's visible or not before calling it, so it may be something to cleanup on the talon side. It might be nice to have something exposed to query whether or not its visible or not already.

**Comment by lunixbochs** [comment]
Is this behavior causing a problem? Do you want me to suppress exceptions from cursor_visible? That could hide legitimate issues with the underlying api.

Even if you could query, a toctou race condition could cause the error to be thrown anyway.

**Comment by fidgetingbits** [comment]
I just assumed you could query if the cursor was already visible or not when we ask for it too unhide, and if it's already visible just don't do anything, and that might avoid the error entirely? Not asking for it to be suppressed if it's happening for another reason. If that's not something easy to avoid then just don't worry about it, and can close.

**Comment by lunixbochs** [comment]
No, I don't think we have a good way to do that. It also doesn't make a ton of sense - each platform's cursor hiding APIs are more intended for you to increment/decrement a hide counter, so you should ideally only be calling show/hide in pairs, which will never result in this error. Cursor hiding is inherently a very leaky abstraction.

So the main question is whether there's a compelling user story for outright suppressing the exception. If one comes up, I would consider doing it. We could also log, ignore, and continue - rather than raising it to the caller.

**Comment by fidgetingbits** [comment]
_
