### ISSUE TITLE
Context for beta and dragon

### ISSUE THREAD

**Issue by AndreasArvidsson** [talonvoice/talon#442]
Now with a new dfa improvements we can do more complex grammar. Would be nice to have the way to only have this enabled on the beta. Ditto with dragon.

**Comment by lunixbochs** [comment]
I believe we do have `speech.engine: wav2letter`

What sort of grammar are you looking to build that won't work on Dragon? Cursorless already doesn't work there.

**Comment by AndreasArvidsson** [comment]
It was general request from the community meeting we have right now. Cursorless is one example. Just a way to enable voice commands only if the engine supports them is the general idea

**Comment by lunixbochs** [comment]
This doesn't make much sense for cursorless, because the user will just not be able to use cursorless anyway, so they'll uninstall it.

I want to be cautious about this because fragmentation inside a repo like knausj_talon could be very poor ux.

**Comment by AndreasArvidsson** [comment]
I don't think that a dragon context is something we going to use in cursorless. It was just general request. 
But we are going to add grammar to cursorless that requires the new dfa.

**Comment by lunixbochs** [comment]
I still suggest doing that on a branch at first, rather than fragmenting your grammar across public/beta based on scope.

**Comment by AndreasArvidsson** [comment]
That is a solution. The reason I raised this issue was that you said in an earlier discussion that a beta specific context would be easy to implement. I understand that you want to avoid fragmentation.

**Comment by lunixbochs** [comment]
I'm just expressing caution about the actual use. beta/public scope is potentially a bad abstraction to ship to release branches of community repos, but probably fine for local user scripts.

As I'm thinking this through, I can see moderate gaps in the UX for naive branch matching:

- User was on beta, switches to public. They have an old knausj_talon (or cursorless) install with some `talon.branch: beta` matches in it. Some of their regularly used commands no longer work, despite public Talon now supporting the features the plugin author was trying to gate.
- User was on beta, switches to another non-public release that also supports the features, commands get disabled despite having feature-level support for them.
- knausj_talon developer is using the beta, and ships a feature that completely breaks aspects of the public release. They don't see the problem due to branch matching.

I'm not saying outright no, but it's an opportunity to consider whether there's a better way to do this and explore the overall pros/cons.
