### ISSUE TITLE
Feature Request: Allow user latency be settable

### ISSUE THREAD

**Issue by riberajo** [talonvoice/talon#50]
This would allow users to adapt the latency with their proficiency

**Comment by lunixbochs** [comment]
This has been possible since 0.0.7.11. Create a file at `~/.talon/draconity.ini` with these contents:

```
[draconity]
timeout = 80
```

Adjust timeout (it's measured in milliseconds) based on your proficiency. The default if you don't supply a config file is 80. If you're using the beta engine, draconity.ini is read when Talon restarts. Otherwise, it's read when you restart Dragon. Updates to the file without restarting Dragon won't affect latency.

There's also `timeout_incomplete` for phrases that aren't finished, but I don't know the default value offhand so I haven't included it.

**Comment by dylan-chong** [comment]
@lunixbochs Please update your comment regarding the information below from issue #76

> the solution is to place the file in `~/.talon/draconity.ini` rather than `~/.talon/.sys/draconity.ini`

**Comment by lunixbochs** [comment]
Fixed!
