### ISSUE TITLE
[linux] talon-rust: Trayicon missing

### ISSUE THREAD

**Issue by Kn0rk** [talonvoice/talon#611]
Talon (beta) Build:
114-0.3.1-
57
571
574

System:
Ubuntu 22.04 X11 with i3

No trayicon (that hold the menu with the entries „About Talon“, „Microphone“,…) appears when talon is started. This makes settings unavailable. 

Going back to running version 114-0.3.1-63-g48c8 resolves the issue.

**Comment by splondike** [comment]
It turns out there are two ways of doing system tray icons under Linux. Talon-Qt used the old way I think (which i3's status bar supports), Talon-Rust does it the new way.

So you have a couple of options in the absence of 1st party support: you can run a status tray that supports the newer method, or you can 'proxy' the newer method to the older method. I've only looked into the latter, all you need to do is run the [snixembed](https://git.sr.ht/~steef/snixembed) application and then reboot Talon and you should get the icon back.

**Comment by Kn0rk** [comment]
Thanks for your response. I will try that program but since i have more issues I am thinking of switching to a better supported distro. 
If i remember correctly talon requires X11 for keyboard controls etc. So switching to wayland+sway would not help.

**Comment by trapier** [comment]
I confirm snixembed [(comment)](https://github.com/talonvoice/talon/issues/611#issuecomment-1523256848) does the trick.  Am running i3-wm 4.22-3 on Arch Linux. Used the [stable AUR](https://git.sr.ht/~steef/snixembed#packages) for Arch.  Didn't even have to restart Talon!

Thanks Kn0rk for filing and splondike for the leg work!

**Comment by Kn0rk** [comment]
I can confirm as well.

**Comment by saidelike** [comment]
I am not sure if this is related but on Windows (and after a sleep/restore), the icon is gone (at least once, I haven't tryed reproducing). Version beta 0.3.1-582-g7ca1

**Comment by lunixbochs** [comment]
That's unrelated, please file a new issue
