### ISSUE TITLE
Displayed version inside Windows settings/Applications 

### ISSUE THREAD

**Issue by ebundy** [talonvoice/talon#629]
On Windows, I notice that the version displayed is wrong : it seems that the version is always 0.1 even when I installed the last public : 0.4.
![image](https://github.com/talonvoice/talon/assets/15986712/13803273-d5ec-47bb-bd03-baebe6545849)

**Comment by lunixbochs** [comment]
it's kind of annoying to fix this because it's stored in the HKLM registry path which we need admin to update, and I'm not templating the installer right now either so it's hardcoded as 0.1 there. For now just read version out of Talon's about window. (Maybe I can remove the version entirely from the installer page)

**Comment by ebundy** [comment]
> (Maybe I can remove the version entirely from the installer page)

Yes, makes more sense to have no version displayed than a wrong one

**Comment by lunixbochs** [comment]
next talon installer will display no version
