### ISSUE TITLE
It’s free, but not open source?

### ISSUE THREAD

**Issue by atljoseph** [talonvoice/talon#665]
So, is this product open source?
- does not look like it. 
- the repo says it’s for issues only. 

If it is free, but not open source, what is the intention?
- It’s hard to tell. 
- what are you doing with user data?
- are you gonna try to sell something in the future? 
- what’s the roadmap?
- When is your next release planned?

Since I can’t tell, not going to try it. 
- looks promising though. 
- is this project actually still alive?
- Is it gonna be here next year?
- ability to understand the source is key. 

If you aren’t charging for the product, and folks cannot freely modify or access (or fix) the source, then what is the incentive to make updates and maintain things and add features?

165 issues here… open issues… 

Thank you. Please. A close competitor, Serenade, has pretty much already died. I’m pretty sure folks also don’t want that to happen here.

**Comment by timo** [comment]
check the list of closed issues sorted by last updated to see that issues are still being closed regularly.

https://github.com/talonvoice/talon/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc

**Comment by atljoseph** [comment]
Wow. Ok. I see that now. 

But still. What is the intention?

Where is it going?

What am I signing up for by installing it and considering to rely upon it? 

(Mac loves to break stuff)

How is user data treated?

**Comment by timo** [comment]
please check out the EULA: https://talonvoice.com/EULA.txt

**Comment by lunixbochs** [comment]
Talon is under active development. It's actively supported and has been since 2017.
It's not going away. I work on it full time.
User data is taken seriously, see the EULA.
Talon is free because it's very important to me that people who really need it are able to use it without major restrictions.
Users voluntarily support Talon on the Patreon, which gives you access to a version that is updated more often than the public version.

**Comment by atljoseph** [comment]
Oh. Then that’s cool. I like grassrootish support
